model: "quartznet12x1_abcfjwz"

AudioToTextDataLayer:
    max_duration: 16.7
    trim_silence: false
    normalize_transcripts: false

AudioToMelSpectrogramPreprocessor:
    sample_rate: 16000
    window_size: 0.02
    window_stride: 0.01
    window: "hann"
    normalize: "per_feature"
    n_fft: 512
    features: 64
    dither: 0.00001
    pad_to: 16
    stft_conv: false

SpectrogramAugmentation:
    rect_masks: 5
    rect_time: 120
    rect_freq: 50

JasperEncoder:
    activation: "relu"
    conv_mask: true

    jasper:
      - filters: 256
        repeat: 1
        kernel: [33]
        stride: [2]
        dilation: [1]
        dropout: 0.0
        residual: false
        separable: true

      - filters: 256
        repeat: 1
        kernel: [33]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 256
        repeat: 1
        kernel: [33]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 256
        repeat: 1
        kernel: [33]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 256
        repeat: 1
        kernel: [39]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 256
        repeat: 1
        kernel: [39]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 256
        repeat: 1
        kernel: [39]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 1
        kernel: [51]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 1
        kernel: [51]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 1
        kernel: [51]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 1
        kernel: [63]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 1
        kernel: [63]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 1
        kernel: [63]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 512
        repeat: 1
        kernel: [75]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: true
        separable: true

      - filters: 1024
        repeat: 1
        kernel: [1]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: false

labels: [' ', 'a', 'b', 'c', 'd', 'e', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'x', 'y', 'à', 'á', 'â', 'ã', 'è', 'é', 'ê', 'ì', 'í', 'ò', 'ó', 'ô', 'õ', 'ù', 'ú', 'ý', 'ă', 'đ', 'ĩ', 'ũ', 'ơ', 'ư', 'ạ', 'ả', 'ấ', 'ầ', 'ẩ', 'ẫ', 'ậ', 'ắ', 'ằ', 'ẳ', 'ẵ', 'ặ', 'ẹ', 'ẻ', 'ẽ', 'ế', 'ề', 'ể', 'ễ', 'ệ', 'ỉ', 'ị', 'ọ', 'ỏ', 'ố', 'ồ', 'ổ', 'ỗ', 'ộ', 'ớ', 'ờ', 'ở', 'ỡ', 'ợ', 'ụ', 'ủ', 'ứ', 'ừ', 'ử', 'ữ', 'ự', 'ỳ', 'ỵ', 'ỷ', 'ỹ', 'f', 'j', 'w', 'z']